### ISSUE TITLE
There are some problems with the Transformation Matrices issued by the Voxelmorph!

### ISSUE THREAD

**Issue by boveiri** [voxelmorph/voxelmorph#266] opened 2021-01-24 22:22 UTC
Hi, I have some problems with the Transformation Matrices issued by the Voxelmorph. It will be highly appreciated if someone can guide me since I am almost at the end of a research project.

I used the Voxelmorph for 2D multimodal co-registration i.e. the registration of a patient's CT on his/her own MR image. The big picture of the system is as follows:

![1](https://user-images.githubusercontent.com/52887476/105644851-2222ef00-5ead-11eb-9937-530dc628eaf1.jpg)

But there is a problem when I want to calculate TRE (Target Registration Error) using my manually annotated landmarks. Actually, when I apply the output of the network with the shape of (6, ) as an Affine Transformation Matrix to my moving image using SpatialTransformer layer hosted in the Neuron package, everything is good and my moved (warped) image is generated correctly. But, when I want to apply the output of the network with the shape of (6, ) as an Affine Transformation Matrix to my moving image using e.g. PIL.Image.transform or using simple matrix multiplication with the coordination of my landmarks to compute the TRE, the results are not as expected and most of the landmarks would fall outside of the image, though the warped image has some slight transformation.

For example, for the following pair of images, the output of the network is the following Transformation Matrix (the subplots are moving image, fix image, and warped image, respectively):

![WhatsApp Image 2021-01-25 at 01 44 42](https://user-images.githubusercontent.com/52887476/105645371-577d0c00-5eb0-11eb-931c-d96206356f79.jpeg)

Network_Output = [0.05199242, -0.07193471, -2.9393158,  0.11451177, -0.01375515, 0.57087]

Original_Landmark_Location = [95, 134]

Moved_Landmark_Location = [-7.5, 4.9] = np.array(Network_Output).reshape(2, 3) @ np.array(Original_Landmark_Location)

As it can be seen, whole the foreground of warped image is inside the image, but the calculated Moved_Landmark_Location goes far outside the image using the affine transformation matrix outputted by the Voxelmorph! The inputted fix and moving images (CT and MR) are both in the (256, 256, 1) shape.

Many thanks for your time and energy.

**Comment by adalca** [comment] 2021-01-24 23:36
Hi @boveiri 

> There are some problems with the Transformation Matrices issued by the Voxelmorph

I think the problem is how you're using them. There's a couple of places the problem could be:

- the SpatialTransformer layer takes a displacement affine matrix (i.e. without the identity map), and adds the identity map to it during the transform. So I'd recommend first adding the identity 2x2 matrix to the affine.  
- The affine matrix is the one that warps the moving pixels to the fixed space, which means that the resulting field is in the space of the fixed image (i.e. it tells us for every location in the fixed space where to grab pixels from the moving image), so in a sense this deformation is backwards from what you expect. To move points from the moving to the fixed, you therefore need to first take the inverse affine.  

so you need to add identity, invert, and then apply this to the annotations.

**Comment by boveiri** [comment] 2021-01-25 19:46
Dear Adrian, many thanks for your guidance, though I am somewhat confused with adding the identity 2x2 matrix to the transformation one because the transformation matrix is a 2x3 matrix and cannot be added with a 2x2 matrix!

But if I have properly understood, I need to add a [0, 0, 1] row as the third row of the transformation matrix outputted by the Voxelmorph so that I have the following transformation matrix for the image in my previous comment:

Network_Output = [0.05199242, -0.07193471, -2.9393158, 0.11451177, -0.01375515, 12.57087] ->2x3

Valid_Transformation_Matrix = [[0.05199242, -0.07193471, -2.9393158], [0.11451177, -0.01375515, 12.57087], [0, 0 ,1]] -> 3x3

Afterwards I used TFM_inv = np.linalg.inv(np.array(Valid_Transformation_Matrix)) to produce the inverted matrix that gave me the following array:

TFM_inv = [[-1.82860552,    9.56297878, -125.58981208], [-15.22316036,    6.91185672, -131.6337281 ], [0.,     0.,    1.]] -> 3x3

but when I multiply a location of annotation i.e. Landmark_Location = [95, 134] -> 2x1  adding 1 as the third row -> [95, 134, 1] -> 3x1

TFM_inv @ [95, 134, 1] = [982, -651, 1] !!! where both the fix and moving image are in (256, 256, 1) shape, and the warped image outputted by the SpatialTransform show a very light transformation between the moving and warped images.

Please help me if I have any mistakes in the computations.

**Comment by adalca** [comment] 2021-01-25 21:13
@boveiri I meant add identity to the non-translation part of the affine:

```
aff = np.array([[0.05199242, -0.07193471, -2.9393158], [0.11451177, -0.01375515, 12.57087], [0, 0, 1]])
aff[:2, :2] += np.eye(2)
inv_aff = np.linalg.inv(aff)
inv_aff @ [95, 134, 1] # gives array([100.71829837, 111.42841393,   1.        ])
```

**Closed** 2021-01-26 22:08 UTC
Labels: voxelmorph

**Comment by boveiri** [comment] 2021-01-31 17:11
Dear Adrian, I don't know how to thank you! Your help is highly appreciated.

But it seems there are somethings more than adding 2x2 Identity matrix. For example, here is the warped MR image transformed based on the following Affine transformation matrix by the SpatialTransformer layer:

TFM=np.array([[ 1.0169007e-01,  4.2508245e-02,  1.5823326e+01], [-3.9284952e-02, -8.4735174e-03,  3.4517705e+00], [0, 0, 1]])

![WhatsApp Image 2021-01-31 at 20 34 35](https://user-images.githubusercontent.com/52887476/106391742-2ba7dc00-6404-11eb-80ea-8d82ee6f86f9.jpeg)

But when we directly transform the image using matrix multiplication or PIL.Image.transform function, we get the following:

TFM[:2, :2] += np.eye(2)
TFM_inv=np.linalg.inv(TFM)
dMR1 = dMR1.transform((size, size),Image.AFFINE, data=TFM_inv.flatten()[:6], resample=Image.NEAREST)

![07122-1](https://user-images.githubusercontent.com/52887476/106391609-87be3080-6403-11eb-8d50-965c85dfcb6b.png)

(annotations are transformed using simple @ multiplication, and show that the transformed image produced by PIL.Image.transform is correctly transformed) 
I found that there are sensible errors in image translations and some in rotations.

**Comment by adalca** [comment] 2021-01-31 17:53
@boveiri 

Can you show the *entire* code in a code block? How do you transform the image and the annotations with `@` or with PIL ? Otherwise I'm not quite sure of the details. There's a few issues that have to do with space choices -- for example, the default in voxelmorph is to affine transform about the center of the image (not top-left corner). Other systems might require an affine matrix with respect to the top left corner. Also, just a reminder that to warp the annotations you need to use `TFM_inv`, but to warp the image (the same image that the anotations are on!) you need to use `TFM`. This is because of how interpolation algorithms work -- if you need to warp an entire grid, you need the inverse transform of warping specific precise points.

**Comment by boveiri** [comment] 2021-01-31 21:00
Thank you for your timely response. Yes, I use TFM for calculating the new locations of annotations in the warped image, while I use TFM_inv  for PIL.Image.transform function since this function use the inverted of the transformation matrix (I am confused as it is the inverse of what you told me!). The source code is as follows:

`points=np.array([[128, 147, 1], [128, 120, 1], [128, 172, 1], [128, 61, 1], [128, 222, 1], [197, 146, 1], [62, 146, 1]]) 
TFM=np.array([[ 1.0169007e-01,  4.2508245e-02,  1.5823326e+01], [-3.9284952e-02, -8.4735174e-03,  3.4517705e+00], [0, 0, 1]])
TFM[:2, :2] += np.eye(2)
TFM_inv=np.linalg.inv(TFM)

dMR1 = Image.fromarray(dMR); size = dMR.shape[0]
dMR1 = dMR1.transform((size, size),Image.AFFINE, data=TFM_inv.flatten()[:6], resample=Image.NEAREST)
dMR = np.asarray(dMR1)

for i in range(points.__len__()):
    new_point = TFM @ points[i]
    f_show_point(new_point)  #this is a function showing any point in the subplot given the location as its input parameter`

I think your note about the origin of the coordination may cause this problem, but how I could solve the problem?

**Comment by adalca** [comment] 2021-02-01 14:31
well we subtract the center coordinate from all the points before transforming them, so I imagine (but have not verified) that simply adding (or subtracting?) the center (so roughly `vol_shape / 2` in each dimension) from the translation component of the affine matrix should do the job.

**Comment by boveiri** [comment] 2021-02-01 16:44
Thanks for the guidance, but I examined this before and it doesn't work! The below plot is an example:

![07122-new](https://user-images.githubusercontent.com/52887476/106487856-5a878600-64c8-11eb-9f98-e03806815a02.png)

The leftmost subplot is the CT image, the rightmost subplot is the original MRI, and the middle is the warped MRI transformed by the SpatialTransformer layer (network's output). 

Firstly, I subtracted the half of the image's size from x and y, then I transformed the points using simple @ (matrix manipulation). Finally, I added the half of the image's size to x and y and showed the points in the middle subplots (red points). As it can be seen, the red points are not matched with the warped image transformed by the SpatialTransformaer layer. (Yellow points are landmarks in the CT image, and I showed them in the warped MRI to show that the Voxelmorph works properly to register the pair of inputted images but there is something wrong with the transformation produced by the network).

**Comment by boveiri** [comment] 2021-02-02 17:37
![07122-6-New](https://user-images.githubusercontent.com/52887476/106638392-10baa080-6599-11eb-9d14-7bcf01fa69d1.png)

The left subplot is the MRI (warped) transformed by the SptialTransformer layer (network's output), where the red points are annotations firstly subtracted by the half of image's size, then transformed by @, then added with the half of image's size, and finally illustrated.

The right subplot is the MRI (warped) transformed by TFM_inv (inverse of the transformation matrix) using PIL.Image.transform() function, where the red points are annotations transformed by @ (simple matrix manipulation).

It is obvious that the applying the transformation doesn't need to subtract/add half of image's size. Nevertheless, the output images produced by SpatialTransformer layer has major difference with other approaches like PIL.Image.transform(), and unfortunately this problem has halted our project for calculating TRE (Target Registration Error). It is appreciated if you have any solution or alternative for us.

**Comment by adalca** [comment] 2021-02-02 18:20
@boveiri ,

I am a bit confused -- have you tried using solely VoxelMorph functions to warp your images and annotations? 

I understand that you want to play with other methods to transform images and annotations, but are you finding that the voxelmorph functions are doing it wrong? (e.g. using `SpatialTransformer` for images, and `vxm.tf.utils.point_spatial_transformer` for points)

**Comment by boveiri** [comment] 2021-02-03 18:42
Thank you for your support and nice guidance. Actually, I was not aware of `vxm.tf.utils.point_spatial_transformer` for points, and if it can obviate the problem, we can use it. In the first step, I tried to warp the moving image using `neuron.layers.SpatialTransformer()` but I faced the following error or such ones several times:

Lets my moving image be MR_org with the shape (256, 256), and the flatten affine transformation matrix be TFM with shape (6, ). I tried to warp the moving image using the following code:

```
tImMoving = tf.convert_to_tensor(dMR_org, dtype=tf.float32)
taffine =tf.convert_to_tensor(TFM, dtype=tf.float32)
tImWarped = sess.run(neuron.layers.SpatialTransformer()([tImMoving, taffine]), feed_dict={tImMoving: dMR_org, taffine: TFM})
```
but the error is:

```
File "D:/Python/Reg/Draft_Show_Marks.py", line 55, in <module>
    tImWarped = sess.run(neuron.layers.SpatialTransformer()([tImMoving, taffine]), feed_dict={tImMoving: dMR_org, taffine: TFM1})
  File "C:\Users\Hamidreza\Anaconda3\envs\myenv\lib\site-packages\keras\engine\topology.py", line 594, in __call__
    self.build(input_shapes)
  File "D:\Python\Reg\voxelmorph-lib\voxelmorph\ext\neuron-lib\neuron\layers.py", line 117, in build
    if trf_shape[-1] != self.ndims:
IndexError: tuple index out of range
```
I inspected your code and found that line 117 in layers.py is about non-affine transformations! please help if I need to reshape the affine transformation matrix to any other shapes. (however, I tried shapes like (2,3) or (3,2) for transformation matrix, or (256, 256, 1) for the inputted image, but just the lines of error were changed).

**Comment by adalca** [comment] 2021-02-03 20:36
@boveiri 
you seem to be using quite old vode, we've moved SpatialTransformer from neurite to voxelmorph a long time ago, and have moved to tf 2.0 quite a bit ago, so I'm not quite sure which version you have. The following works for us:

```
vol_shape = [128, 128]
keras_vol_shape = [1] + vol_shape + [1]

im = np.random.uniform(size=keras_vol_shape)
aff = np.random.randn(1, 2, 3)  

warped_im = vxm.layers.SpatialTransformer()([im, aff])
print(im.shape, aff.shape, warped_im.shape)
```

and outputs

```
(1, 128, 128, 1) (1, 2, 3) (1, 128, 128, 1)
```

**Comment by boveiri** [comment] 2021-02-03 22:15
Thank you for your helpful comments in a timely manner, and sorry for my simple questions. Actually, yes, I am using the old versions of neuron and voxelmorph as I was infected with COVID and had severe problems for some months. I finally could issue the problem of using `neuron.layers.SpatialTransformer()` to properly transform the moving image to the warped image in a correct manner. If we can transform the points using `vxm.tf.utils.point_spatial_transformer()` properly, we will be able to close this issue very successfully.

Lets the followings be the list of points and the affine transformation:

```
points=np.array([[128, 147, 1], [128, 120, 1], [128, 172, 1], [128, 61, 1], [128, 222, 1], [197, 146, 1], [62, 146, 1]]) 
TFM=np.array([[ 1.0169007e-01,  4.2508245e-02,  1.5823326e+01], [-3.9284952e-02, -8.4735174e-03,  3.4517705e+00], [0, 0, 1]]) 
```
Could you please show me an example how to get proper warped points using `vxm.tf.utils.point_spatial_transformer()` function?

I have some questions, too, and it is appreciated if you could guide:

1- Is the vxm.tf.utils.point_spatial_transformer() able to work with affine transformations?
2- I have tf version 1.15.0 and cannot transfer to tf version 2.0, let me know if the `vxm.tf.utils.point_spatial_transformer()` works with my tf version or if you have any old implementation of the function that could work for me?

Thanks and regards,

**Comment by adalca** [comment] 2021-02-04 00:10
sorry to hear about COVID

Here's some code that works for me, but this is using tf2.3:

```
vol_shape = 256, 256  # volume shape
TFM[:2, :2] += 1       # add identity

field = vxm.utils.affine_to_shift(TFM, vol_shape, shift_center=True)[np.newaxis, ...]
points_tf = tf.convert_to_tensor(points[np.newaxis, :, :2], dtype=tf.float32)
field_tf = tf.convert_to_tensor(field, dtype=tf.float32)
warped_pts = vxm.utils.point_spatial_transformer([points_tf, field_tf])[0, ...]
```

**Comment by boveiri** [comment] 2021-02-04 15:28
Thanks for your sympathy. If the problem can be solve I will be better! I used the `vxm.utils.point_spatial_transformer()` function to warp the points but its results are same as we use simple matrix multiplication like `TFM @ points` . I don't know it is important or not but since I am using the `neuron.layers.SpatialTransformer()` i.e. the old version, I simply copy/pasted `point_spatial_transformer()` function from voxelmorph/utils.py to the voxelmorph/neuron/utils.py, but I think it is OK and it caused no error, since the main work is done by the `affine_to_shift()` function situated in the neuron.utils library.

I also used affine_to_shift() function and simply adding the filed to the points, but the result is the same:

![07122-6-New-New](https://user-images.githubusercontent.com/52887476/106913740-91a0a600-6719-11eb-90f7-1c6cf86b8890.png)

With some experiments, I made confidant that there is an inconsistency between the warped image outputted by the `SpatialTransformer()` for affine transformation with other transformation methods to warp the points, since the output of the warped points are same both with `TFM @ points` and `vxm.utils.point_spatial_transformer()` (and both are inconsistent with the warped image by the SpatialTransformer().

**Comment by adalca** [comment] 2021-02-05 14:04
@boveiri , I don't think there's any inconsistency between the functions.

I wrote up a quick colab to verify this, and they seem to be consistent to me. Perhaps this can help you figure out where your problem is. https://colab.research.google.com/drive/1V0CutSIfmtgDJg1XIkEnGteJuw0u7qT-?usp=sharing

**Comment by boveiri** [comment] 2021-02-07 19:44
I think I could finally find the source of the error, and solve the problem. First of all, the annotations in the previous post are incorrectly illustrated since I should use the `TFM_inv` instead of `TFM` as you correctly mentioned in the previous comments. However, this was not the case as I always tried both `TFM` and its inverse in the experiments. 

After converting the affine transformation matrix to its corresponding field using `affine_to_shift()` function, I represented the field using a flow diagram, and here is the result:

![07122-6-flow1](https://user-images.githubusercontent.com/52887476/107157072-4eec0180-6997-11eb-8c83-bc051b648eba.png)

But this field seems to be somehow weird! as it tries to compress the image in x (horizontal) axis, while conversely the image should be expanded along this axis. Finally, after many experiments, I could detect that if we exchange the axes in the field (x->y, and y->x), the field works correctly, so I used the following simple instruction to exchange the axes:

`fieldAff[...,[0, 1]] = fieldAff[...,[1, 0]]`

Then applying the concluded field to the points using the `point_spatial_transformer()` function would resulted correct locations:

![07122-6-correct](https://user-images.githubusercontent.com/52887476/107157330-cbcbab00-6998-11eb-9110-d8de3f5d0e3c.png)

I don't know it is routine or a bug in the implementations, but for warping the image using the `SpatialTransformer()`, there is no need to such a manipulation in the affine field.

I hope this topic can be helpful for others, and I sincerely thank for your timely responses and helpful comments.

**Comment by adalca** [comment] 2021-02-07 20:16
@boveiri  yes, this is an issue of indexing standards. We mention it in the `SpatialTransformer` `indexing` parameter (see documentation) and you can find more info at e.g. https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html

Basically in numerical work we usually index in matrix notation [row, column, ...], but for images that get plotted (and annotations) e.g. in matplotlib, you'll often see a flip in the first two axes, because the graphics convention is to list the x (horizonal axis) first. So it's basically a clash of two indexing standards. We stick to matrix notation in VoxelMorph (although the SpatialTransformer allow for both), which is why when visualizing you need to flip the axes.
