### ISSUE TITLE
pytorch erros

### ISSUE THREAD

**Issue by HP192080042** [voxelmorph/voxelmorph#128] opened 2019-11-29 13:04 UTC
pytorch_version      An error occurred:
![image](https://user-images.githubusercontent.com/53810832/69870688-af8ba300-12eb-11ea-85a4-84b583cd4116.png)

Can you help me solve this problem? Thank you!

**Comment by HP192080042** [comment] 2019-11-29 13:05
@adalca

**Comment by adalca** [comment] 2019-11-29 14:22
I don't think this has to do with pytorch, it's just about loading your own data. Feel free to change the data loader to be bale to deal with your own data. 

This is a Duplicate of #126 , 

You can also see other descriptions like https://github.com/voxelmorph/voxelmorph/issues/16#issuecomment-439627356

**Closed by adalca** 2019-11-29 14:22 UTC
