### ISSUE TITLE
Error while trying to register with Voxelmorph

### ISSUE THREAD

**Issue by Hoda1394** [voxelmorph/voxelmorph#378] opened 2021-12-14 18:47 UTC
I am using ./scripts/tf/register.py to register an image with the atlas with voxelmorph model and I am getting the following error.

`File "./scripts/tf/register.py", line 65, in <module>
    warp = vxm.networks.VxmDense.load(args.model, input_model=None).register(moving, fixed)
TypeError: load() got an unexpected keyword argument 'input_model'`

python 3.7.11
tensorflow 2.6

I installed voxelmorph from PyPI.

**Comment by tphankr** [comment] 2021-12-23 18:15
me too, do you solve the problem? thanks.
+ I had two img0004.nii.gz and img0001.nii.gz in Data folder.
 And then I typed ./scripts/tf/register.py --moving ./Data/img0001.nii.gz --fixed ./Data/img0004.nii.gz --moved warp.nii.gz --model vxm_dense_brain_T1_3D_mse.h5 --warp warp.nii.gz --gpu 1
and had the same error: 
![image](https://user-images.githubusercontent.com/37217354/147277646-4f1370a9-4a17-4d72-8160-172c26b4537f.png)
+ I also typed fully ( --multichannel =0.5 ) but I don't know what parameter of --multichannel ? and have below error. 
![image](https://user-images.githubusercontent.com/37217354/147277996-1f7e3619-7005-49e6-81dc-1532b7d7038a.png)

Please help us. Thank  you, @Hoda1394 , @adalca , @ahoopes  and all.

**Comment by adalca** [comment] 2021-12-23 18:16
Can you tell us which voxelmorph version you are using -- latest from github, or the pip/pypi version?

**Comment by tphankr** [comment] 2021-12-23 18:20
Thank you @adalca, 
Yes, I have typed pip install voxelmorph. 

Thanks.

**Comment by tphankr** [comment] 2021-12-23 18:58
Thank you @adalca .
I have created the environment to do again. 
-------------------- My status computer: ------------------
1) tensorflow-gpu==2.6.0
2) I have download the code from mu40's github (https://github.com/JJGO/voxelmorph) with version 506 commits and used 
python setup.py install. And we had: 
![image](https://user-images.githubusercontent.com/37217354/147279148-d05fe146-d042-477f-824f-0d356f59ac92.png)

Finnally, I ran again of register.py file. The same error is 
TypeError: load() got an unexpected keyword argument 'input_model'
![image](https://user-images.githubusercontent.com/37217354/147280887-beb652c3-8233-49f1-aafa-6d0eae84eb5d.png)
-------------------------------------------The end-----------------------

Question***) Other help: If I use the neurite-oasis.v1.0 dataset. I am confusing which file is moving image/ Fixed image/ Label? ( Although I read on your github but still do not understand clearly) Thank you very much.
![image](https://user-images.githubusercontent.com/37217354/147281732-a0299628-06de-4c27-9c0c-f9b0c6fb2e94.png)

Thanks.

**Comment by Hoda1394** [comment] 2021-12-23 20:00
@tphankr I could solve the issue by installing voxelmorph, neurite, and pystrum from their Github.
[voxelmorph](https://github.com/voxelmorph/voxelmorph)
[neurite](https://github.com/adalca/neurite)
[pystrum](https://github.com/adalca/pystrum)

**Comment by tphankr** [comment] 2021-12-24 03:02
Thank you @adalca and @Hoda1394 and all,
I solved that error by : python 3.7.10; tensorflow 2.7.0 and reference from https://github.com/voxelmorph/voxelmorph/issues/321 , https://github.com/voxelmorph/voxelmorph/issues/378 (@Hoda1394)

Howerver, the .h5 file (https://github.com/voxelmorph/voxelmorph/blob/dev/data/readme.md#models) is not suitable my case. Because my results is black. 
![image](https://user-images.githubusercontent.com/37217354/147310714-69e816a1-48ad-4a26-821f-4440b6137a63.png)
I maybe try to do the train step again.

You can close this issue. Thanks.

**Comment by ahoopes** [comment] 2021-12-24 23:44
Just to clarify - this original issue is caused by a version mismatch with the dev branch scripts and the formal pip release vxm package. Alternatively to @Hoda1394's recommendation, another option is to use the scripts from the master brach, which should always correspond to the most recent pypi release.

@tphankr regarding the above issue, you should first check to make sure your data is preprocessed in the same way described in the top-level readme (you can use the example OASIS dataset as a reference). If you still run into issues, it's probably best to open a new issue.

**Closed as completed by ahoopes** 2021-12-24 23:44 UTC
