### ISSUE TITLE
test_seg.npz

### ISSUE THREAD

**Issue by taipingqu** [voxelmorph/voxelmorph#15] opened 2018-11-15 08:51 UTC
hi,Your paper says that the data is done with freesurfer. Can you elaborate on how test_seg.npz is done with freesurfer?

**Comment by adalca** [comment] 2018-11-17 15:54
Duplicate of #3 . Thanks!

**Closed by adalca** 2018-11-17 15:54 UTC

**Comment by taipingqu** [comment] 2018-11-23 13:08
Thank you.But the image I generated with freesurfer is not clear to you, what is the cause, my command is recon-all xxxx -autorecon1, just the first five steps, how to improve my command if it is wrong.

**Comment by taipingqu** [comment] 2018-11-23 13:09
Thank you.But the image I generated with freesurfer is not clear to yours, what is the cause, my command is recon-all xxxx -autorecon1, just the first five steps, how to improve my command if it is wrong.

**Comment by taipingqu** [comment] 2018-11-23 13:20
![634983538633989614](https://user-images.githubusercontent.com/35133044/48945455-65981080-ef65-11e8-98c8-d8fff8055ec8.jpg)
![857173843744983484](https://user-images.githubusercontent.com/35133044/48945476-78aae080-ef65-11e8-9443-5222ac205842.jpg)
On the right is the image I generated.

**Comment by taipingqu** [comment] 2018-11-24 01:45
Thanks @adalca.I downloaded the original data from ADNI, the slice thickness is 1mm, the shape is approximately 256*204*240, then I preprocessed with freesurfer.After resampling the scans to 256x256x256 with freesurfer, I crop them by the following ammounts: ((48, 48), (31, 33), (3, 29)).

**Comment by taipingqu** [comment] 2018-11-24 01:46
![20181124093858](https://user-images.githubusercontent.com/35133044/48963463-ce1ad800-efcd-11e8-9e2c-2c93ba445ab8.jpg)

**Comment by taipingqu** [comment] 2018-11-24 01:50
Add: We use files in .nii format.

**Comment by adalca** [comment] 2018-11-24 22:06
Ah i see. SO in the screenshot above, it is not the exact same subject, just a similar one?

In that case, perhaps it's worth just running affine registration (e.g. using ANTs) to our atlas, to make sure they're in the same space. Other than that, you should be good to go to use VoxelMorph.

**Comment by taipingqu** [comment] 2018-11-29 11:59
Hi,
I am trying to run the command:
/home/weidu/anaconda2/envs/tensorflow-gpu/bin/python /home/weidu/qtp_code/voxelmorph/src/train.py
Using TensorFlow backend.
2018-11-29 19:56:36.457616: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-29 19:56:36.457652: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-29 19:56:36.457663: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-11-29 19:56:36.457671: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-29 19:56:36.457679: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX512F instructions, but these are available on your machine and could speed up CPU computations.
2018-11-29 19:56:36.457687: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-11-29 19:56:36.677129: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.683
pciBusID 0000:b3:00.0
Total memory: 10.91GiB
Free memory: 10.48GiB
2018-11-29 19:56:36.677166: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2018-11-29 19:56:36.677175: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2018-11-29 19:56:36.677196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:b3:00.0)
Traceback (most recent call last):
  File "/home/weidu/anaconda2/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/weidu/anaconda2/envs/tensorflow-gpu/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/weidu/anaconda2/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension size, given by scalar input 0, must be non-negative but is -1 for 'spatial_transformer_1/split' (op: 'Split') with input shapes: [], [?,160,192,224,3] and with computed input tensors: input[0] = <-1>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weidu/qtp_code/voxelmorph/src/train.py", line 151, in <module>
    train(**vars(args))
  File "/home/weidu/qtp_code/voxelmorph/src/train.py", line 77, in train
    model = networks.unet(vol_size, nf_enc, nf_dec)
  File "/home/weidu/qtp_code/voxelmorph/src/networks.py", line 104, in unet
    y = nrn_layers.SpatialTransformer(interp_method='linear', indexing='xy')([src, flow])
  File "/home/weidu/anaconda2/envs/tensorflow-gpu/lib/python3.5/site-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "../ext/neuron/neuron/layers.py", line 159, in call
    trf_split = tf.split(trf, trf.shape[-1], axis=-1)
  File "/home/weidu/anaconda2/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1214, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/home/weidu/anaconda2/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3261, in _split
    num_split=num_split, name=name)
  File "/home/weidu/anaconda2/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/weidu/anaconda2/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/home/weidu/anaconda2/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/weidu/anaconda2/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/weidu/anaconda2/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/weidu/anaconda2/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension size, given by scalar input 0, must be non-negative but is -1 for 'spatial_transformer_1/split' (op: 'Split') with input shapes: [], [?,160,192,224,3] and with computed input tensors: input[0] = <-1>.

**Comment by adalca** [comment] 2018-11-30 03:19
Interesting, I've never seen this. Can you give us the the version of tensorflow you are running?

**Comment by taipingqu** [comment] 2018-11-30 08:04
OK，I have already adjusted it. I used to be CUDA8.0, cudnn5.0, so my version of tensorflow is up to 1.2.1, but after I upgraded CUDA and cudnn successfully, I modified the tensorflow-gpu version.

**Comment by taipingqu** [comment] 2018-11-30 08:16
Regarding the test, what do you call "Put test filenames in data/test_examples.txt" like this 1_vol.npz, 1_seg.npz?

**Comment by adalca** [comment] 2018-11-30 13:00
yes, exactly!

**Comment by taipingqu** [comment] 2018-12-03 07:32
Hi Adrian. Sorry to bother again,I've run affine registration to talairach using FreeSurfer (the default parameters used), but I don't feel right. What parameters does your paper use FreeSurfer for affine registration adjustment? Could you tell me the command?Thank you very much.

**Comment by taipingqu** [comment] 2018-12-04 04:42
Using TensorFlow backend.
2018-12-04 12:35:28.728277: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2018-12-04 12:35:28.931350: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:b3:00.0
totalMemory: 10.91GiB freeMemory: 10.46GiB
2018-12-04 12:35:28.931397: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:b3:00.0, compute capability: 6.1)
  0 0.760 0.760
  1 0.000 0.380

The first line of results is the demo you gave.The following(1 0.000 0.380) is the data I generated. I think it is a big problem in affine registration.

**Comment by adalca** [comment] 2018-12-09 12:53
We used default testing parameters. 

Can you tell me what you are trying to do with the second post? Is your goal to register images? test Dice outcome? Did you train your own model?

**Comment by adalca** [comment] 2018-12-12 18:03
@taipingqu I don't think the affine registration is here. Can you:

For each of: our initial model, and your trained model, do the following:

1. load the model using load_weights
2. register one image using model.predict()
3. show me the resulting warped image?

**Comment by taipingqu** [comment] 2018-12-16 12:32
I still don't understand how affinely aligned is obtained. Could you tell me?

**Comment by adalca** [comment] 2018-12-16 16:44
Hi @taipingqu, As mentioned in a post above, I think you should just run affine alignment with a popular tool like ANTs. That should do a good job given the images you showed me.

**Comment by taipingqu** [comment] 2018-12-17 00:47
Thanks.

**Comment by taipingqu** [comment] 2019-01-08 03:13
Hi Adrian.Does asep.mgz generated by freesurfer also need affine registration? (such as using ANTs)

**Comment by adalca** [comment] 2019-01-08 22:33
if i understand your question, yes you need to transform it using the affine matrix from the respective subject file, so that it's in the same space as the transformed subject file.

**Comment by ZQYzqyZ** [comment] 2019-03-21 02:57
Hi adalca:
        I want to know What are the role of test_vol.npz and test_seg.npz?
        Which .npz file should be imported in line 66 of the 'train_miccai2018.py'?
       Thank you very much.I am looking forward to your reply.

**Comment by adalca** [comment] 2019-03-29 11:42
hi @ZQYzqyZ, `test_vol.npz` and `test_seg.npz` are example volume and segmentation. 
if by line 66 you mean the data loading, that line requires a folder where all your data is. Please see this other answer to your questions [here](https://github.com/voxelmorph/voxelmorph/issues/16#issuecomment-467180368)
